image:
  file: .gitpod.Dockerfile
tasks:
  - name: setup
    before: |-
      # Download the latest release
      curl -s https://api.github.com/repos/thatdot/quine/releases/latest \
      | grep "browser_download_url.*jar" \
      | cut -d : -f 2,3 \
      | tr -d \" \
      | wget -i -

      # Create a Quine sym-link
      ln -s $(ls -tr quine-*.jar | tail -1) quine.jar

      # Download the sample data
      curl -L https://that.re/attempts -o attempts.json

      # get Astra CLI
      mkdir bin
      curl -Ls "https://dtsx.io/get-astra-cli" | bash

    command: |-
      # Open README in VS Code (or default IDE)
      gp open README.md

ports:
  - port: 8080
    onOpen: open-browser
    visibility: private
